### ISSUE TITLE
Shouldn't allow you to interact with the page again until the doors finishing opening

### ISSUE THREAD

**Issue by andrewnicols** [tholman/elevator.js#10]
Unless this is an open-door elevator, when it reaches the top you should not be able to interact with the page again until the doors have opened.

**Comment by seanjohnson08** [comment]
How cool would it be to actually have an [elevator gate](https://www.google.com/search?q=elevator+gate) cover the entire screen, and then open when it gets to the top? This would fix your issue and make the experience a lot better in one go. :) (I suggested a gate, because doors would not be see-through)

**Comment by dwkns** [comment]
Unless there was a glass doors option.

**Comment by syk0saje** [comment]
+1 for the elevator gate!

**Comment by YMIndustries** [comment]
+1

**Comment by tholman** [comment]
This is one of those open face elevators, that would get you totally killed in a zombie scenario. Sadly the way it has to be :dancer:
